movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id', views.detail, name='detail')
]

vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views

movie_resource = MovieResource()

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api', include(movie_resource.urls))
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

# Create your models here.


class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        excludes = ['date_created']

movies/models.py
from django.db import models
from django.utils import timezone


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Movie


def index(request):
    # get list of movies
    movies = Movie.objects.all()
    return render(request, 'movies/index.html', {'movies': movies})

    # filter list
    # Movie.objects.filter(release_year=1984)

    # # get specific movie
    # Movie.objects.get(id=1)


def detail(requiest, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})

vidly/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

movies/templates/movies/detail.html
{% extends 'base.html' %} {% block content %}
<dl>
  <dt>Title</dt>
  <dd>{{ movie.title }}</dd>
  <dt>Genre</dt>
  <dd>{{ movie.genre }}</dd>
  <dt>Stock</dt>
  <dd>{{ movie.number_in_stock }}</dd>
</dl>
{% endblock%}

movies/templates/movies/index.html
{%extends 'base.html' %} {% block content %}
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Stock</th>
      <th>Daily Rate</th>
    </tr>
  </thead>
  <tbody>
    {% for movie in movies%}
    <tr>
      <td>
        <a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a>
      </td>
      <td>{{ movie.genre }}</td>
      <td>{{ movie.number_in_stock }}</td>
      <td>{{ movie.daily_rate }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

    <title>Vidly</title>
  </head>
  <body>
    <!-- As a link -->
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="#">Vidly</a>
    </nav>
    <main class="container">
      {% block content %} {% endblock %}
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %} {% block content %}
<a href="{% url 'movies:index' %}">Movies</a>
{% endblock %}